[features]
seeds = false
skip-lint = false

[programs.devnet]
privacy_matcher = "B2GB1aku91TAm2eRs3AAYiC9d5Xo35TdnbdA1mtqYuTG"
vol_matcher = "73Zhah3R7mzDUMM2rKM7A4E7WYkv3aGUGmNrCj7uEqNn"
jpy_matcher = "FZf6Zcw6nBzeLKtw4o4o9LFXzjxRa2poAdJxmLieuHF8"
event_matcher = "6d8JHEuia8cJEVFDcQqeLUFnGhCo9igzqVLam1H9cpum"
macro_matcher = "9E7yvQkrVj8i9RtBTkFPeDS9ZaVRodBHV9zTyL1fuKQV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
